"""
theme_css.py — Inject Streamlit UI CSS that matches the active plot theme.

Call ``inject_theme_css()`` on every page AFTER ``set_theme()`` to skin
the entire Streamlit chrome (background, sidebar, widgets, buttons, tabs,
alerts, etc.) to match the current plot palette.

Usage (in any page):
    from theme_css import inject_theme_css
    inject_theme_css()          # reads THEME from engine.config
"""

import streamlit as st
from engine.config import THEME


def _build_css() -> str:
    """Return a complete ``<style>`` block derived from the active THEME."""

    bg       = THEME["bg"]
    surface  = THEME["surface"]
    surface2 = THEME["surface2"]
    border   = THEME["border"]
    text     = THEME["text"]
    muted    = THEME["text_muted"]
    subtle   = THEME["text_subtle"]
    font     = THEME["font_family"]
    cyan     = THEME["cyan"]
    green    = THEME["green"]
    red      = THEME["red"]
    amber    = THEME["amber"]
    blue     = THEME["blue"]

    # Determine if we're in a "light" theme (bright bg → dark text)
    # by checking if bg luminance > 0.5
    _r = int(bg[1:3], 16) / 255
    _g = int(bg[3:5], 16) / 255
    _b = int(bg[5:7], 16) / 255
    _lum = 0.299 * _r + 0.587 * _g + 0.114 * _b
    is_light = _lum > 0.5

    # Hover / active shades
    hover_bg  = surface2 if not is_light else "#e8eaed"
    active_bg = cyan

    # Button text: always white on coloured bg for primary buttons
    btn_primary_text = "#ffffff" if is_light else bg

    return f"""<style>
/* ═══════════════════════════════════════════════════════════════════
   BeginSeq Studio — Dynamic UI Theme  (auto-generated by theme_css.py)
   ═══════════════════════════════════════════════════════════════════ */

/* ── 0. Streamlit CSS custom properties (feeds into iframes) ──── */
:root,
[data-testid="stAppViewContainer"],
.stApp {{
    --primary-color: {cyan};
    --background-color: {bg};
    --secondary-background-color: {surface};
    --text-color: {text};
    --font: {font};
}}

/* ── 1. Root / page background ──────────────────────────────────── */
.stApp {{
    background-color: {bg};
    color: {text};
    font-family: {font};
}}
[data-testid="stAppViewContainer"] {{
    background-color: {bg};
}}
[data-testid="stHeader"] {{
    background-color: rgba(0,0,0,0);
}}

/* ── 2. Sidebar ─────────────────────────────────────────────────── */
[data-testid="stSidebar"] {{
    background-color: {surface} !important;
    border-right: 1px solid {border};
}}
[data-testid="stSidebar"],
[data-testid="stSidebar"] *,
[data-testid="stSidebar"] [data-testid="stMarkdownContainer"],
[data-testid="stSidebar"] [data-testid="stWidgetLabel"],
[data-testid="stSidebar"] .stMarkdown {{
    color: {text} !important;
}}
[data-testid="stSidebarNav"] span,
[data-testid="stSidebarNavLink"],
[data-testid="stSidebarNavLink"] span,
[data-testid="stSidebarNavLink"] p {{
    color: {muted} !important;
}}
[data-testid="stSidebarNavLink"]:hover,
[data-testid="stSidebarNavLink"]:hover span {{
    color: {cyan} !important;
    background-color: {hover_bg} !important;
}}
/* Active nav link */
[data-testid="stSidebarNavLink"][aria-current="page"],
[data-testid="stSidebarNavLink"][aria-current="page"] span {{
    color: {cyan} !important;
}}

/* ── 3. Typography ──────────────────────────────────────────────── */
.stApp, .stApp * {{
    color: {text};
}}
.stMarkdown, [data-testid="stMarkdownContainer"],
[data-testid="stMarkdownContainer"] p,
[data-testid="stMarkdownContainer"] span,
[data-testid="stMarkdownContainer"] li,
[data-testid="stMarkdownContainer"] td,
[data-testid="stMarkdownContainer"] th {{
    color: {text} !important;
}}
.stMarkdown h1, .stMarkdown h2, .stMarkdown h3,
.stMarkdown h4, .stMarkdown h5, .stMarkdown h6,
[data-testid="stHeading"],
[data-testid="stHeading"] * {{
    color: {text} !important;
}}
[data-testid="stWidgetLabel"],
[data-testid="stWidgetLabel"] p,
[data-testid="stWidgetLabel"] label {{
    color: {muted} !important;
}}
[data-testid="stCaptionContainer"],
[data-testid="stCaptionContainer"] p {{
    color: {subtle} !important;
}}
/* Selectbox / multiselect displayed value */
div[data-baseweb="select"] span,
div[data-baseweb="select"] input {{
    color: {text} !important;
}}
/* Number input display */
.stNumberInput label, .stTextInput label, .stTextArea label {{
    color: {muted} !important;
}}

/* ── 4. Widget inputs ───────────────────────────────────────────── */
.stTextInput input,
.stNumberInput input,
.stTextArea textarea {{
    background-color: {surface} !important;
    color: {text} !important;
    border-color: {border} !important;
}}
div[data-baseweb="select"] {{
    background-color: {surface};
    color: {text};
}}
div[data-baseweb="select"] > div {{
    background-color: {surface} !important;
    color: {text} !important;
    border-color: {border} !important;
}}
/* Dropdown menu */
div[data-baseweb="popover"] {{
    background-color: {surface} !important;
    border-color: {border} !important;
}}
div[data-baseweb="popover"] li {{
    background-color: {surface} !important;
    color: {text} !important;
}}
div[data-baseweb="popover"] li:hover {{
    background-color: {hover_bg} !important;
}}
/* Slider */
.stSlider [data-baseweb="slider"] div {{
    background-color: {border};
}}
.stSlider [data-testid="stThumbValue"],
.stSlider [data-testid="stTickBarMin"],
.stSlider [data-testid="stTickBarMax"] {{
    color: {muted};
}}

/* ── 5. Buttons ─────────────────────────────────────────────────── */
/* Primary (Run / main CTA) */
[data-testid="stBaseButton-primary"],
[data-testid="stBaseButton-primary"] p,
[data-testid="stBaseButton-primary"] span {{
    background-color: {cyan} !important;
    color: {btn_primary_text} !important;
    border: none !important;
}}
[data-testid="stBaseButton-primary"]:hover {{
    opacity: 0.85;
}}
/* Secondary */
[data-testid="stBaseButton-secondary"],
[data-testid="stBaseButton-secondary"] p,
[data-testid="stBaseButton-secondary"] span {{
    background-color: transparent !important;
    color: {cyan} !important;
    border-color: {border} !important;
}}
[data-testid="stBaseButton-secondary"] {{
    border: 1px solid {border} !important;
}}
[data-testid="stBaseButton-secondary"]:hover {{
    border-color: {cyan} !important;
    background-color: {hover_bg} !important;
}}
/* Download buttons */
.stDownloadButton > button,
.stDownloadButton > button p,
.stDownloadButton > button span {{
    background-color: {surface} !important;
    color: {cyan} !important;
    border: 1px solid {border} !important;
}}
.stDownloadButton > button:hover {{
    border-color: {cyan} !important;
    background-color: {hover_bg} !important;
}}
/* Form submit button */
[data-testid="stFormSubmitButton"] > button,
[data-testid="stFormSubmitButton"] > button p,
[data-testid="stFormSubmitButton"] > button span {{
    background-color: {cyan} !important;
    color: {btn_primary_text} !important;
    border: none !important;
}}
/* Link buttons */
[data-testid="stBaseButton-elementToolbar"],
[data-testid="stBaseButton-minimal"] {{
    color: {muted} !important;
}}
[data-testid="stBaseButton-elementToolbar"]:hover,
[data-testid="stBaseButton-minimal"]:hover {{
    color: {cyan} !important;
}}

/* ── 6. Tabs ────────────────────────────────────────────────────── */
.stTabs [data-baseweb="tab-list"] {{
    background-color: transparent;
    gap: 2px;
    border-bottom: 1px solid {border};
}}
.stTabs [data-baseweb="tab"] {{
    color: {muted};
    background-color: transparent;
}}
.stTabs [data-baseweb="tab"]:hover {{
    color: {text};
}}
.stTabs [aria-selected="true"] {{
    color: {cyan} !important;
    border-bottom-color: {cyan} !important;
}}

/* ── 7. Expanders ───────────────────────────────────────────────── */
[data-testid="stExpander"] {{
    background-color: {surface};
    border: 1px solid {border};
    border-radius: 8px;
}}
[data-testid="stExpander"] summary {{
    color: {text};
}}
[data-testid="stExpander"] summary:hover {{
    color: {cyan};
}}

/* ── 8. DataFrames / Tables ─────────────────────────────────────── */
/* st.dataframe container (glideDataEditor is in an iframe — limited) */
[data-testid="stDataFrame"] {{
    border: 1px solid {border};
    border-radius: 6px;
    background-color: {bg};
}}
/* st.table — full HTML table, fully stylable */
[data-testid="stTable"] {{
    color: {text} !important;
}}
[data-testid="stTable"] table {{
    background-color: {bg} !important;
    border-collapse: collapse;
}}
[data-testid="stTable"] thead th {{
    background-color: {surface} !important;
    color: {text} !important;
    border-bottom: 2px solid {border} !important;
    padding: 8px 12px;
    font-weight: 600;
}}
[data-testid="stTable"] tbody td {{
    background-color: {bg} !important;
    color: {text} !important;
    border-bottom: 1px solid {border} !important;
    padding: 6px 12px;
}}
[data-testid="stTable"] tbody tr:nth-child(even) td {{
    background-color: {surface} !important;
}}
[data-testid="stTable"] tbody tr:hover td {{
    background-color: {hover_bg} !important;
}}
/* Markdown-rendered HTML tables */
.stMarkdown table {{
    background-color: {bg} !important;
    border-collapse: collapse;
    width: 100%;
}}
.stMarkdown table th {{
    background-color: {surface} !important;
    color: {text} !important;
    border: 1px solid {border} !important;
    padding: 8px 12px;
}}
.stMarkdown table td {{
    background-color: {bg} !important;
    color: {text} !important;
    border: 1px solid {border} !important;
    padding: 6px 12px;
}}
.stMarkdown table tr:nth-child(even) td {{
    background-color: {surface} !important;
}}

/* ── 9. Progress bar ────────────────────────────────────────────── */
.stProgress > div {{
    background-color: {surface};
}}
.stProgress [role="progressbar"] {{
    background-color: {cyan};
}}

/* ── 10. Metrics ────────────────────────────────────────────────── */
[data-testid="stMetric"] {{
    background-color: {surface};
    border: 1px solid {border};
    border-radius: 8px;
    padding: 12px 16px;
}}
[data-testid="stMetricValue"] {{
    color: {cyan};
}}
[data-testid="stMetricLabel"] {{
    color: {muted};
}}

/* ── 11. Alerts (info / warning / success / error) ──────────────── */
[data-testid="stAlert"] {{
    border-radius: 8px;
    background-color: {surface} !important;
}}
[data-testid="stAlert"] p,
[data-testid="stAlert"] span {{
    color: {text} !important;
}}

/* ── 12. File uploader ──────────────────────────────────────────── */
[data-testid="stFileUploaderDropzone"] {{
    background-color: {surface} !important;
    border-color: {border} !important;
    color: {muted};
}}

/* ── 13. Horizontal rule ────────────────────────────────────────── */
.stApp hr {{
    border-color: {border};
}}

/* ── 14. Radio & Checkbox ───────────────────────────────────────── */
.stRadio label,
.stRadio label span,
.stCheckbox label,
.stCheckbox label span {{
    color: {text} !important;
}}

/* ── 14b. Multiselect tags ────────────────────────────────────────── */
[data-baseweb="tag"] {{
    background-color: {surface2} !important;
    color: {text} !important;
    border-color: {border} !important;
}}
[data-baseweb="tag"] span {{
    color: {text} !important;
}}

/* ── 14c. File uploader text ─────────────────────────────────────── */
[data-testid="stFileUploaderDropzone"] span,
[data-testid="stFileUploaderDropzone"] small,
[data-testid="stFileUploaderDropzone"] p,
[data-testid="stFileUploaderDropzone"] button {{
    color: {muted} !important;
}}

/* ── 14d. Status / spinner text ──────────────────────────────────── */
[data-testid="stStatusWidget"],
[data-testid="stStatusWidget"] * {{
    color: {text} !important;
}}

/* ── 14e. Streamlit toolbar / menu icon ──────────────────────────── */
[data-testid="stToolbar"] button svg {{
    fill: {muted};
    stroke: {muted};
}}

/* ── 15. Scrollbar (subtle) ─────────────────────────────────────── */
::-webkit-scrollbar {{
    width: 8px;
    height: 8px;
}}
::-webkit-scrollbar-track {{
    background: {bg};
}}
::-webkit-scrollbar-thumb {{
    background: {border};
    border-radius: 4px;
}}
::-webkit-scrollbar-thumb:hover {{
    background: {muted};
}}

/* ── 16. Tooltip / popover ──────────────────────────────────────── */
[data-testid="stTooltipContent"] {{
    background-color: {surface2} !important;
    color: {text} !important;
    border: 1px solid {border} !important;
}}

/* ── 17. Code blocks ────────────────────────────────────────────── */
.stApp pre, .stApp code {{
    background-color: {surface} !important;
    color: {cyan} !important;
    border: 1px solid {border};
}}
</style>"""


def inject_theme_css() -> None:
    """Inject a ``<style>`` block that skins Streamlit to the active THEME.

    Call this once per page, **after** ``set_theme()``.
    Also overrides Streamlit's internal theme config so that components
    rendered inside iframes (e.g. ``st.dataframe``) pick up the right
    background / text colours.
    """
    # ── 1. Override Streamlit's runtime config for iframe-based widgets ──
    try:
        from streamlit import _config
        _config.set_option("theme.primaryColor",             THEME["cyan"])
        _config.set_option("theme.backgroundColor",          THEME["bg"])
        _config.set_option("theme.secondaryBackgroundColor", THEME["surface"])
        _config.set_option("theme.textColor",                THEME["text"])
    except Exception:
        pass  # fail silently if internal API changes

    # ── 2. CSS injection for the parent document ────────────────────────
    st.markdown(_build_css(), unsafe_allow_html=True)
